### ISSUE TITLE
Removing Virtual Items adds Arsenal action

### ISSUE THREAD

**Issue by saintblood** [ImperialAlex/XLA_FixedArsenal#13]
hi,

removing virtual items by using BIS-functions or their XLA-version adds the arsenal action to the box. (id a3-feedback tracker: 0022814)
   BIS_fnc_removeVirtualWeaponCargo;
   BIS_fnc_removeVirtualBackpackCargo;
   BIS_fnc_removeVirtualItemCargo;
   BIS_fnc_removeVirtualMagazineCargo;

problem should be
[_object,_classes,_isGlobal,>>true<<,-1,0] call XLA_fnc_addVirtualItemCargo;
but i dont know how it would affect xla in total... better if someone who really knows what xla does changes that stuff ;)

anyways, a "false" would make more sense (and is less work than controlling it by a parameter) considering that an action not added with AmmoboxInit or adding content might have its reasons for the missionmaker.

regards
Saint

ps: huge thanks for fixing what BI still didnt *hands over cookie*

**Comment by ImperialAlex** [comment]
Hey, thanks for reporting this :)
N.B.: Don't use the bis_fnc_* functions when you're working with this mod, it won't change the virtualcargo for XLA_fnc_arsenal since they use different variables.

I didn't realize this was a thing, good spot! I'll add in a parameter. Even though I agree "false" would be the better default, I try to keep things as similar to the vanilla version as possible.

How critical is this bug for you? Unless it's preventing you from creating something, I'd like to bundle this into the next 'proper' update, however if you need this fixed quickly I can push out a little hotfix.

**Comment by saintblood** [comment]
not urgent, since it only adds a second action to the fancy desired one with 50% moar colors, fix in the next proper update is fine.

for now i use a quick&dirty workarround by simply removing all actions from the ammobox before i add my own ;)
