### ISSUE TITLE
Script version

### ISSUE THREAD

**Issue by saintblood** [ImperialAlex/XLA_FixedArsenal#18]
Hi there,

a script version of fixed arsenal would be much appreciated, which could be included in the map.

i spent a while on research, to get the functions in the mission file all that is necessary is to include a new file containing a list of all functions (and ofc the functions), lets call it *functions.h*, and include this file in the description.ext (samples below)

description.ext
```
class CfgFunctions
{
	#include "xla_fixedarsenal\functions.h"
};
```

functions.h
```
class XLA
{
	tag = "XLA";
	class functions
	{
        file = "XLA_FixedArsenal\functions\Inventory"; //path to the functions in the mission file.. to keep it simple just like in the mod-version
        class addVirtualBackpackBlacklist {};
        ....
        list of all functions like in the config
        
        
	};
};
```
tested it before submitting this request.. works.

only thing i can not get to work is the dialog itself as i have no idea how those dialogs in arma work.

if its to much of change drop the idea, would only be nice for vanilla arma or lightweight modpack servers (cba agm tfar) to avoid the need of users to get the modversion of xla

regards
saint

**Comment by ImperialAlex** [comment]
I've thought about this, mostly from a ease-of-development standpoint.
Anytime I change something in the mod and want to test it, I need to re-launch the game.
A mission/script version would be much more convenient for me, too ;) 

I've tried porting over previous versions to mission-only but found it didn't work too well.
However, I have since then made my functions 100% independent from vanilla configs, so chances are good it might work better this time around.

I'm currently trying to figure out why merging the changes from 1.42 back into my modded version is failing. Once I get a version out that works with #bipods, I have some major rewriting to do, see #15 for details. I'll probably try and create a "mission" version for development before I attempt those rewrites.

If it works out, I'll just add in a second sample mission with the "mission" version. 
It's going to be a pain in the .... to make sure it's always up-to-date with the 'real' version, though.

**Comment by ImperialAlex** [comment]
Will be included in the next release

**Comment by ImperialAlex** [comment]
This is proving to be quite tricky. I can't get the createDisplay call to work properly and I'm running out of ideas pretty quickly. Maybe something related to CfgScriptPaths being used by the addon/that not being supported by description.ext?

**Comment by ImperialAlex** [comment]
Even if I load the addon with the CfgScriptPaths entry, I still can't get the GUI to show up. 
Unless somebody can help me figure out mission-based UI a bit more I'll have to abandon this :(

**Comment by saintblood** [comment]
will experiment with it, maybe i get lucky

details on XLA_FixedArsenal/scripts/RscDisplayFixedArsenal.sqf would be nice.. cant imagine what it does and confused my self right now by trying to find out :laughing: 

as far as i know the opening of the gui is done within the case "open" in fn_arsenal.sqf

**Comment by ImperialAlex** [comment]
the "Open" part ends by calling
`(finddisplay 312) createdisplay "RscDisplayFixedArsenal";`

According to [the biki for findDisplay](https://community.bistudio.com/wiki/findDisplay)  312 is apparently the IDD for the Zeus display. Not sure why we'd want the arsenal to be a child of the zeus display but I assume Karel Mořický had a good reason ;) 

I'm not sure of the findDisplay even returns something meaningful in the mission version -- this will be my next line of investigation :)

**Comment by saintblood** [comment]
i have a wild guess why it is child of curators interface... there is a module the allmighty can drop on a units head and change its loadout as he desires.. so my guess is that it is built that way to be compatible with that and not mess up.. since curator interface could be locked..


i build upon the stable xla but thanks

**Comment by ImperialAlex** [comment]
After previous attempts where unsuccessful I don't think I'll be able to realistically port this mod to a mission.
