### ISSUE TITLE
Freeze when accessing arsenal on another box

### ISSUE THREAD

**Issue by saintblood** [ImperialAlex/XLA_FixedArsenal#25]
when you access arsenal after you opened it on another container it shows no loadingscreen but freezes the game while arsenal is loading the other box..

some sort of loadingscreen/info would be nice to not frighten the users..

havent tested, just came to my mind right now:
does the new preloading on a per box level increase loadingtimes on missionstart? if so, does it mess with the loadingscreen or anything? - will investigate tomorrow if you didnt happen to answer by then

**Comment by ImperialAlex** [comment]
This is sadly a known issue. 
Multiple calls to the arsenal will work fine as long as they have an ammobox. 
The first "non-ammobox" call will also show the loadscreen, but any calls (non-ammobox or ammobox) after that wont' show the loadingscreen. Functionality isn't affected but it's a bit annoying. Especially since after hours of debugging I can't explain why it happens... bis_fnc_startloadingscreen is called...but doesn't  show the screen.

The preload-per-box doesn't affect mission load times by default  since the "preload" is done the first time you open the arsenal (each box needs to do it once when you open it).
If you manually add the "preload" call to a mission init make sure to pass in the ammobox (see function header for details) to get the right thing preloaded :)

**Comment by ImperialAlex** [comment]
Since this doesn't affect functionality I'm going to stop worrying about it. #wontfix
